# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    Template:
      Count: 1 # Template 의 count 값이 peer 의 개수
    Users:
      Count: 2 # 기 등록된 application 사용자 인증서 개수

  - Name: Org2
    Domain: org2.example.com
    Template:
      Count: 1 
    Users:
      Count: 1
       
  - Name: Org3
    Domain: org3.example.com
    Template:
      Count: 1 
    Users:
      Count: 1
